#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.
SUBLIME_VERSION=3
rm -rf $ZSH/sublime/User
cp -R ~/Library/Application\ Support/Sublime\ Text\ $SUBLIME_VERSION/Packages/User $ZSH/sublime2/User
