#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

SUBLIME_VERSION=3
# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ $SUBLIME_VERSION/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime/User" "$sublime_dir"

# Grab the Soda theme
cd "$sublime_dir"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
